package model;
// Generated 22-mar-2016 12:47:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.io.Serializable;
 
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
 
/**
 * Login generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Login  implements java.io.Serializable {

    private static final long serialVersionUID = 1094801825228386363L;
     private int idLogin;
     private String email;
     private String password;
     private Set usuarioLogins = new HashSet(0);

    public Login() {
    }

	
    public Login(int idLogin, String email, String password) {
        this.idLogin = idLogin;
        this.email = email;
        this.password = password;
    }
    public Login(int idLogin, String email, String password, Set usuarioLogins) {
       this.idLogin = idLogin;
       this.email = email;
       this.password = password;
       this.usuarioLogins = usuarioLogins;
    }
   
    public int getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUsuarioLogins() {
        return this.usuarioLogins;
    }
    
    public void setUsuarioLogins(Set usuarioLogins) {
        this.usuarioLogins = usuarioLogins;
    }

   //validate login
    public String validateUsernamePassword() {
        boolean valid = LoginDAO.validate(email, password);
        if (valid) {
            HttpSession session = SessionBean.getSession();
            session.setAttribute("email", email);
            return "admin";
        } else {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                            "Incorrect Username and Passowrd",
                            "Please enter correct username and Password"));
            return "login";
        }
    }
    
        //logout event, invalidate session
    public String logout() {
        HttpSession session = SessionBean.getSession();
        session.invalidate();
        return "login";
    }


}


