package model;
// Generated 22-mar-2016 12:47:11 by Hibernate Tools 4.3.1



/**
 * UsuarioLogin generated by hbm2java
 */
public class UsuarioLogin  implements java.io.Serializable {


     private int idUsuarioUsuarioLogin;
     private Login login;
     private Usuario usuario;

    public UsuarioLogin() {
    }

    public UsuarioLogin(Login login, Usuario usuario) {
       this.login = login;
       this.usuario = usuario;
    }
   
    public int getIdUsuarioUsuarioLogin() {
        return this.idUsuarioUsuarioLogin;
    }
    
    public void setIdUsuarioUsuarioLogin(int idUsuarioUsuarioLogin) {
        this.idUsuarioUsuarioLogin = idUsuarioUsuarioLogin;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


